#!/bin/bash
# Generated by MSTBx Runner Generator v0.8.5

# --- CONTROL FLAGS ---
eq=on
md_init=off
md_continue=off
# ----------------------

# --- NAMD CONFIG ---
NAMD="namd2"
OPTS="+p8"
# --------------------

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}MSTBx Runner initiated (SMD Protocol)${NC}"

if [ "$eq" == "on" ]; then
    echo -e "${YELLOW}Starting Equilibration...${NC}"
    cd 02nvt && $NAMD $OPTS nvt.confg > nvt.log || exit 1
    cd ..
    cd 03npt && $NAMD $OPTS npt.confg > npt.log || exit 1
    cd ..
fi

if [ "$md_init" == "on" ]; then
    echo -e "${YELLOW}Starting SMD Production...${NC}"
    cd 04md && $NAMD $OPTS smd.confg > smd.log || exit 1
    cd ..
fi

echo -e "${GREEN}SMD simulation steps completed.${NC}"
