name: mstbx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - gromacs>=2024
  - openbabel
  - openmm>=8.1
  - pdbfixer>=1.9
  - mdanalysis>=2.7
  - mdtraj>=1.9
  - networkx=2.3
  - pip:
      - -e ".[test]"
