#! Generated by MSTBx PSFGenSolSMD module
set psf step1_pdbreader.psf 
set pdb step1_pdbreader.pdb 
set sol solvated
set output mol 
set salt 0.15 

mol new $psf type psf waitfor all 
mol addfile $pdb type pdb waitfor all 

set all [atomselect top all]
set selanchor [atomselect top "resid 1"]
set selpull [atomselect top "resid 76"]

# Orienting to Z axis
set com_anchor [measure center $selanchor]
set com_pull [measure center $selpull]
set axis [vecsub $com_pull $com_anchor]
set M [transvecinv $axis]
$all move $M
set M [transaxis y -90]
$all move $M

set minmax [measure minmax $all]
set min [lindex $minmax 0]
set max [lindex $minmax 1]

# Apply Standard padding + Extra pad for SMD in Z+
set p [expr 18.0]
set p_extra [expr 60.0]

set minx [expr [lindex $min 0] - $p]
set maxx [expr [lindex $max 0] + $p]
set miny [expr [lindex $min 1] - $p]
set maxy [expr [lindex $max 1] + $p]
set minz [expr [lindex $min 2] - $p]
set maxz [expr [lindex $max 2] + $p + $p_extra]

package require solvate
solvate $psf orientedtoZ.pdb -minmax [list [list $minx $miny $minz] [list $maxx $maxy $maxz]] -o $sol -s W

mol delete all
package require autoionize
autoionize -psf $sol.psf -pdb $sol.pdb -cation SOD -anion CLA -sc $salt -o ionized -seg ION

# Final report from ACTUAL coordinates
mol delete all
mol new ionized.psf
mol addfile ionized.pdb
set all [atomselect top all]
set final_minmax [measure minmax $all]
set f_min [lindex $final_minmax 0]
set f_max [lindex $final_minmax 1]
set f_center [measure center $all]

set fout [open "step3_pbcsetup.str" w]
puts $fout "SET A = [expr [lindex $f_max 0] - [lindex $f_min 0]]"
puts $fout "SET B = [expr [lindex $f_max 1] - [lindex $f_min 1]]"
puts $fout "SET C = [expr [lindex $f_max 2] - [lindex $f_min 2]]"
puts $fout "SET XCEN = [lindex $f_center 0]"
puts $fout "SET YCEN = [lindex $f_center 1]"
puts $fout "SET ZCEN = [lindex $f_center 2]"
close $fout

$all writepdb $output.pdb
$all writepsf $output.psf

if {0} {
    package require psfgen
    psfcontext reset
    readpsf $output.psf pdb $output.pdb
    hmassrepart
    writepsf $output.hmr.psf
    writepdb $output.hmr.pdb
}
quit
