#! Generated by MSTBx PSFGenSol module
set psf reset.psf 
set pdb reset.pdb 
set sol solvated
set output mol 
set salt 0.15 

mol new $psf type psf waitfor all 
mol addfile $pdb type pdb waitfor all 

set model [atomselect top "all"] 
set center [measure center $model]
set minmax [measure minmax $model]
set min [lindex $minmax 0]
set max [lindex $minmax 1]
set dimens [vecsub $max $min]

# STRICT CUBIC LOGIC - Using longest dimension of the molecule
set max_dim [expr {max([lindex $dimens 0],[lindex $dimens 1],[lindex $dimens 2])}]
set p 18.0
set boxlen [expr ($max_dim + 2 * $p) / 2 + 1]

# Define cubic box centered at molecule center
set boxmin [list [expr [lindex $center 0] - $boxlen] [expr [lindex $center 1] - $boxlen] [expr [lindex $center 2] - $boxlen]]
set boxmax [list [expr [lindex $center 0] + $boxlen] [expr [lindex $center 1] + $boxlen] [expr [lindex $center 2] + $boxlen]]

# Override with specific granular padding ONLY if provided by user
if {None != "None" || None != "None" || None != "None" || None != "None" || None != "None" || None != "None"} {
    set minx [expr [lindex $min 0] - 18.0]
    set maxx [expr [lindex $max 0] + 18.0]
    set miny [expr [lindex $min 1] - 18.0]
    set maxy [expr [lindex $max 1] + 18.0]
    set minz [expr [lindex $min 2] - 18.0]
    set maxz [expr [lindex $max 2] + 18.0]
    set boxmin [list $minx $miny $minz]
    set boxmax [list $maxx $maxy $maxz]
}

# Solvate and Ionize
package require solvate
solvate $psf $pdb -minmax [list $boxmin $boxmax] -o $sol -s W 

mol delete all 
package require autoionize 
autoionize -psf $sol.psf -pdb $sol.pdb -cation SOD -anion CLA -sc $salt -o ionized -seg ION

# Recentering to 0,0,0
mol delete all 
mol new ionized.psf 
mol addfile ionized.pdb type pdb waitfor all
set all [atomselect top all]
set center [measure center $all]
$all move [transoffset [vecsub {0 0 0} $center]]
$all writepdb $output.pdb 
$all writepsf $output.psf

# Final PBC calculation from ACTUAL atoms (Strictly Square/Cubic)
set wat [atomselect top "all"]
set final_minmax [measure minmax $wat]
set f_min [lindex $final_minmax 0]
set f_max [lindex $final_minmax 1]
set f_vec [vecsub $f_max $f_min]

# Use the maximum extension to ensure a large enough cubic box for NAMD
set L [expr {max([lindex $f_vec 0],[lindex $f_vec 1],[lindex $f_vec 2])}]

set fout [open "step3_pbcsetup.str" w]
puts $fout "SET A = $L"
puts $fout "SET B = $L"
puts $fout "SET C = $L"
puts $fout "SET XCEN = 0"
puts $fout "SET YCEN = 0"
puts $fout "SET ZCEN = 0"
close $fout 

if {0} {
    package require psfgen
    psfcontext reset
    readpsf $output.psf pdb $output.pdb
    hmassrepart
    writepsf $output.hmr.psf
    writepdb $output.hmr.pdb
}
quit
