#!/usr/bin/env python3
"""
ResetPSF.py

Ferramenta simples para resetar arquivos PSF gerados pelo CHARMM-GUI (formato CHARMM)
e gerar arquivos compatíveis com NAMD.
Gera um script TCL para o VMD/psfgen, que lê os arquivos fornecidos, reseta o PSF e salva novos arquivos resetados.

Uso:
    python ResetPSF.py --psf arquivo.psf --pdb arquivo.pdb

Argumentos:
    --psf : Caminho para o arquivo PSF de entrada (formato CHARMM, ex: gerado pelo CHARMM-GUI).
    --pdb : Caminho para o arquivo PDB de entrada.
"""

import sys
import os
import argparse
import logging
import subprocess

def setup_logger():
    """
    Configura o logger para imprimir na tela e salvar em arquivo.
    O formato segue [INFO    2025-06-20 15:30:00] Mensagem.
    """
    logger = logging.getLogger("resetpsf_logger")
    logger.setLevel(logging.INFO)

    # Formato: [INFO    2025-06-20 15:30:00] Mensagem
    formatter = logging.Formatter("[%(levelname)-7s %(asctime)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S")

    # Handler para console
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(formatter)
    logger.addHandler(ch)

    # Handler para arquivo
    fh = logging.FileHandler("resetpsf.log", mode='a')
    fh.setLevel(logging.INFO)
    fh.setFormatter(formatter)
    logger.addHandler(fh)

    return logger

def main():
    logger = setup_logger()

    # Parser de argumentos de linha de comando
    parser = argparse.ArgumentParser(
        description="Reset PSF/PDB generated by CHARMM-GUI (CHARMM format) for NAMD compatibility."
    )
    parser.add_argument(
        "--psf", required=True, help="Input PSF file (CHARMM format, from CHARMM-GUI)."
    )
    parser.add_argument(
        "--pdb", required=True, help="Input PDB file."
    )
    args = parser.parse_args()

    psf = args.psf
    pdb = args.pdb

    logger.info("Resetting PSF/PDB from CHARMM-GUI (CHARMM format) for NAMD compatibility ...")

    # Cria o script TCL para o VMD/psfgen (comentários em português/espanhol)
    script = f"""\
package require psfgen
resetpsf
# Lee el archivo PSF de entrada (formato CHARMM, ex: CHARMM-GUI)
readpsf {psf}
# Asocia coordenadas do arquivo PDB
coordpdb {pdb}
# Activa la opción de escribir enlaces virtuales
vpbonds 1
# Escreve o novo arquivo PSF no formato x-plor (compatível com NAMD)
writepsf x-plor reset.psf
# Escreve o novo arquivo PDB
writepdb reset.pdb
quit
"""
    # Escreve o script em um arquivo
    with open("resetpsf.tcl", "w") as fout:
        fout.write(script)

    # Executa o script TCL usando o VMD em modo texto e captura a saída
    try:
        result = subprocess.run(
            ["vmd", "-dispdev", "text", "-e", "resetpsf.tcl"],
            capture_output=True, text=True, check=True
        )
        # Imprime e salva no log a saída do VMD
        logger.info("VMD output:\n" + result.stdout)
        if result.stderr:
            logger.error("VMD error:\n" + result.stderr)
    except subprocess.CalledProcessError as e:
        logger.error(f"VMD execution failed: {e}")
        if e.stdout:
            logger.error("VMD output:\n" + e.stdout)
        if e.stderr:
            logger.error("VMD error:\n" + e.stderr)

    logger.info("PSF/PDB reset complete for NAMD. Output: reset.psf, reset.pdb")

if __name__ == "__main__":
    main()

