#! Generated by MSTBx PSFGenSol module
set psf step1_pdbreader.psf 
set pdb step1_pdbreader.pdb 
set sol solvated
set output mol 
set salt 0.15 

mol new $psf type psf waitfor all 
mol addfile $pdb type pdb waitfor all 

set model [atomselect top "all"] 
set minmax [measure minmax $model]
set min [lindex $minmax 0]
set max [lindex $minmax 1]

# Apply custom padding per axis
set minx [expr [lindex $min 0] - 18.0]
set maxx [expr [lindex $max 0] + 18.0]
set miny [expr [lindex $min 1] - 18.0]
set maxy [expr [lindex $max 1] + 18.0]
set minz [expr [lindex $min 2] - 18.0]
set maxz [expr [lindex $max 2] + 18.0]

set boxmin [list $minx $miny $minz]
set boxmax [list $maxx $maxy $maxz]

# Solvate and Ionize
package require solvate
solvate $psf $pdb -minmax [list $boxmin $boxmax] -o $sol -s W 

mol delete all 
package require autoionize 
autoionize -psf $sol.psf -pdb $sol.pdb -cation SOD -anion CLA -sc $salt -o ionized -seg ION

# Recentering to 0,0,0
mol delete all 
mol new ionized.psf 
mol addfile ionized.pdb type pdb waitfor all
set all [atomselect top all]
set center [measure center $all]
$all move [transoffset [vecsub {0 0 0} $center]]
$all writepdb $output.pdb 
$all writepsf $output.psf

# Final PBC calculation from ACTUAL atoms
mol delete all
mol new $output.psf
mol addfile $output.pdb
set all [atomselect top all]
set final_minmax [measure minmax $all]
set f_min [lindex $final_minmax 0]
set f_max [lindex $final_minmax 1]
set f_center [measure center $all]

set A [expr [lindex $f_max 0] - [lindex $f_min 0]]
set B [expr [lindex $f_max 1] - [lindex $f_min 1]]
set C [expr [lindex $f_max 2] - [lindex $f_min 2]]

set fout [open "step3_pbcsetup.str" w]
puts $fout "SET A = $A"
puts $fout "SET B = $B"
puts $fout "SET C = $C"
puts $fout "SET XCEN = [lindex $f_center 0]"
puts $fout "SET YCEN = [lindex $f_center 1]"
puts $fout "SET ZCEN = [lindex $f_center 2]"
close $fout 

if {0} {
    package require psfgen
    psfcontext reset
    readpsf $output.psf pdb $output.pdb
    hmassrepart
    writepsf $output.hmr.psf
    writepdb $output.hmr.pdb
}
quit
