#!/bin/bash
# Generated by MSTBx Runner Generator v0.8.5

# --- CONTROL FLAGS ---
eq=on
md_init=off
md_continue=off
# ----------------------

# --- NAMD CONFIG ---
NAMD="namd2" # Or namd3
OPTS="+p8"    # Number of cores or GPU flags
# --------------------

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}MSTBx Runner initiated${NC}"

if [ "$eq" == "on" ]; then
    echo -e "${YELLOW}Starting Equilibration (NVT)...${NC}"
    cd 02nvt && $NAMD $OPTS nvt.confg > nvt.log || exit 1
    cd ..
    
    echo -e "${YELLOW}Starting Equilibration (NPT)...${NC}"
    cd 03npt && $NAMD $OPTS npt.confg > npt.log || exit 1
    cd ..
fi

if [ "$md_init" == "on" ]; then
    echo -e "${YELLOW}Starting Initial Production MD...${NC}"
    cd 04md && $NAMD $OPTS md.confg > md.log || exit 1
    cd ..
fi

if [ "$md_continue" == "on" ]; then
    echo -e "${YELLOW}Continuing Production MD...${NC}"
    # This logic assumes NAMD writes restart files. 
    # For a generic script, we just run the same config if it handles restarts internally
    # Or you can edit the script to point to a specific restart.
    cd 04md && $NAMD $OPTS md.confg >> md.log || exit 1
    cd ..
fi

echo -e "${GREEN}Simulation steps completed successfully.${NC}"
