#! Generated by MSTBx PSFGenMemb module
set psf step4_lipid.psf 
set pdb step4_lipid.pdb 
set sol solvated
set output mol 
set salt 0.15 
set peptidemem 0
set padding 25.0

mol new $psf type psf waitfor all 
mol addfile $pdb type pdb waitfor all

if {$peptidemem} {
    set psf orient.psf 
    set pdb orient.pdb
    set headlipid [atomselect top {lipids and name "P*" and z > 0}]
    set headcom [measure center $headlipid]
    set zheadcom [lindex $headcom 2]
    set pep [atomselect top protein]
    set pepcom [measure center $pep]
    set zpepcom [lindex $pepcom 2]

    set extended 10.0
    set currentd [expr $zheadcom - $zpepcom]
    set z [expr $extended - $currentd]
    $pep moveby [list 0 0 $z]

    set all [atomselect top all]
    $all writepsf orient.psf
    $all writepdb orient.pdb
} 

mol delete all
mol new $psf 
mol addfile $pdb

# Calculate XY size based on lipids/protein - STRICT XY SQUARE LOGIC
set all [atomselect top "lipids and name P or protein"] 
set minmax [measure minmax $all]
set xylen [vecsub [lindex $minmax 1] [lindex $minmax 0]] 
set maxvec [expr {max([lindex $xylen 0],[lindex $xylen 1])}]
set vec [expr $maxvec/2 + 1]

# Z padding: Use user-defined padding (default 25.0 A)
# Total Z box thickness = protein/lipid thickness + 2 * padding
# Padding History: 20.0 (Original), 22.5 (CHARMM-GUI), 25.0 (Current MSTBx)
set zlen [vecsub [lindex $minmax 1] [lindex $minmax 0]]
set zboxpad [expr ([lindex $zlen 2] + (2 * $padding))/2 + 1]

set boxmin [list [expr -$vec] [expr -$vec] [expr -$zboxpad]]
set boxmax [list [expr $vec] [expr $vec] [expr $zboxpad]]

package require solvate
solvate $psf $pdb -minmax [list $boxmin $boxmax] -o $sol -s W 

# Cleanup bad waters
mol delete all
set id [mol new $sol.psf type psf waitfor all]
mol addfile $sol.pdb type pdb waitfor all 
set badw1 [atomselect top "waters and same residue as within 3 of protein"]
# Phosphate groups in CHARMM-GUI are typically around Z +/- 19A
set badw2 [atomselect top "waters and same residue as abs(z) < 20"]
$badw1 set beta 1
$badw2 set beta 1
set allbadwater [atomselect top "name OH2 and beta > 0"]
set seglistwater [$allbadwater get segid]
set reslistwater [$allbadwater get resid]

mol delete all
package require psfgen
resetpsf
readpsf $sol.psf
coordpdb $sol.pdb
foreach segid $seglistwater resid $reslistwater {
   	delatom $segid $resid
}
writepsf ${sol}_removeW.psf
writepdb ${sol}_removeW.pdb

package require autoionize 
autoionize -psf ${sol}_removeW.psf -pdb ${sol}_removeW.pdb -cation SOD -anion CLA -sc $salt -o ionized -seg ION

# Final centering and PBC reporting based on waters (Original strategy)
mol delete all 
mol new ionized.psf 
mol addfile ionized.pdb type pdb waitfor all
set all [atomselect top all]
set center [measure center $all]
$all move [transoffset [vecsub {0 0 0} $center]]

# Measure actual water box for accurate PBC
set wat [atomselect top "waters"]
set final_minmax [measure minmax $wat]
set f_min [lindex $final_minmax 0]
set f_max [lindex $final_minmax 1]

set A [expr [lindex $f_max 0] - [lindex $f_min 0]]
set B [expr [lindex $f_max 1] - [lindex $f_min 1]]
set C [expr [lindex $f_max 2] - [lindex $f_min 2]]

set fout [open "step3_pbcsetup.str" w]
puts $fout "SET A = $A"
puts $fout "SET B = $B"
puts $fout "SET C = $C"
puts $fout "SET XCEN = 0"
puts $fout "SET YCEN = 0"
puts $fout "SET ZCEN = 0"
close $fout 

$all writepdb $output.pdb 
$all writepsf $output.psf

if {0} {
    package require psfgen
    psfcontext reset
    readpsf $output.psf pdb $output.pdb
    hmassrepart
    writepsf $output.hmr.psf
    writepdb $output.hmr.pdb
}
quit
